config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :favorites, only:[:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :user_id, scope: :book_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image
  # , destroy: false　怪しいから削除　あるよなぁ

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2},uniqueness: true
  validates :introduction, length: {maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end

  def after_sign_in_path_for(resorce)
    user_path(current_user.id)
  end

  def after_sign_aut_path_for(resource)
    root_path
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def create
    @book = Book.find(params[:book_id])
    @comment = BookComment.new(book_comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = @book.id
    @comment.save
    redirect_to book_path(@book)
  end

  def destroy
    @comment = BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @comment.destroy
    redirect_to book_path(params[:book_id])
  end



  private
  def book_comment_params
      params.require(:book_comment).permit(:comment)
  end


  def correct_user
    # コメントした本人＋ではないならリダイレクトさせるという表現がしたい
    @comment = BookComment.find(params[:id])

    if current_user.id != @comment.user.id
      redirect_to books_path
    # 正しいユーザーではない場合本一覧に戻す
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user! 
	before_action :correct_user, only: [:edit, :update]


  def show
		@book = Book.find(params[:id])
		@user = @book.user
		@books = Book.new

		@book_comment = BookComment.new
		# あっているかも
  end

  def index
		@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall あれ、これがある、、、ないと思った
		@book = Book.new

		# @bookn = Book.find(params[:id])
		# コメント数を表示させるため新たに記載→each文の中だからいらないかも
  end

  def create
		@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
		@book.user_id = current_user.id
    # 意味：user_idがnilのままだと、子モデルのbookの方が保存できない
  	if @book.save #入力されたデータをdbに保存する。
  	  flash[:notice] = "successfully."
      redirect_to book_path(@book)#保存された場合の移動先を指定。
  	else
			@books = Book.all
  		render action: :index
  	end
  end

  def edit
		@book = Book.find(params[:id])
		

  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
			render "edit"
			
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

	def correct_user
    @book = Book.find(params[:id])
    # まず本を取り出した 重要
    @user = @book.user
    # 本に結びついたユーザーを取り出す
    if current_user != @user
      redirect_to books_path
    # 正しいユーザーではない場合本一覧に戻す
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @book.id)
    @favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user! 
	before_action :baria_user, only: [:edit,:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）、書いてあった
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）？
	 end
	
	def edit
		@user = User.find(params[:id])
	end

  def update
		@user = User.find(params[:id])
		
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render action: :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
		<div class="col-md-8 offset-md-1">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>

						<td>
							<% if book.favorited_by?(current_user) %>
							<!-- もしファボっていたら、だからデリートから描く -->
							  <%= link_to book_favorites_path(book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: pink;"></i>
							    <%= book.favorites.count %>
							  <% end %>
							<% else %>
							  <%= link_to book_favorites_path(book), method: :post do %>
							    <i class="fa fa-heart" aria-hidden="true"></i>
							    <%= book.favorites.count %>
							  <% end %>
							<% end %>
						</td>
						<td>
						  <p>コメント数：<%= book.book_comments.count %></p>
						</td>
					<% end %>
					</tr>
				</tbody>
			</table>
		</div>

app/views/books/_newform.html.erb
<% if book.errors.any? %>
  <h3><%= book.errors.count %>errors prohibited this book from being saved:</h3>
  <% book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>
<%= form_with model: book do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control book_title" %>
	</div>

	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: "form-control book_body" %>
	</div>

	<div class="form-group">
		<%= f.submit class: "btn btn-success" %>
	</div>
<% end %><% if book.errors.any? %>
  <h3><%= book.errors.count %>errors prohibited this book from being saved:</h3>
  <% book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Editing Book</h1>
    <%= render "books/newform", book: @book %>
    <%= link_to "Show", @book, class: "book_#{@book.id}" %>
    <%= link_to "Back", books_path, class: "back" %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<% flash.each do |message_type, message| %>
  <%= message %>
<% end %>
<div class="container px-5 px-sm-0">

	<div class="row">
		<div class="col-md-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>
		<%= render 'books/book' %>
		<!--books一覧 -->

	</div>
</div>

app/views/books/show.html.erb
<div id="notice"></div>
<div class="container">
	<div class="row">
		<div class="col-md-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @books %>

		</div>

		<div class="col-md-8 offset-md-1">
			<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<td>
						<% if @book.favorited_by?(current_user) %>
						<!-- もしファボっていたらというif文、だからデリートから描く -->
						<%= link_to book_favorites_path(@book), method: :delete do %>
						<i class="fa fa-heart" aria-hidden="true" style="color: pink;"></i>
						<%= @book.favorites.count %>
						<% end %>
						<% else %>
						<%= link_to book_favorites_path(@book), method: :post do %>
						<i class="fa fa-heart" aria-hidden="true"></i>
						<%= @book.favorites.count %>
						<% end %>
						<% end %>
					</td>

					<!-- コメント数表示機能 -->
					<td>
						<p>コメント数：<%= @book.book_comments.count %></p>
					</td>

					<% if @user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td>
						<%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %>
					</td>
					<% end %>
				</tr>
			</table>

			<!-- 投稿したコメントと書く場所表示 -->

			<table class="table">
					<% @book.book_comments.each do |book_comment|%>
				<tr>
					<!-- 本のidのユーザー名が出力されてしまっている。 -->
					<td>
						<%= link_to attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"), user_path(book_comment.user) %> <br>
						<%= book_comment.user.name %>
					</td>
					<td>
						<p>コメント数<%= book_comment.comment %></p>
					</td>

					<td>
						<% if book_comment.user_id == current_user.id %>
						<%= link_to "Destroy", book_book_comment_path(@book,book_comment.id), method: :delete, class: "btn-sm btn-danger" %>

						<!-- Bookのidを固定にしたい books/固定/comments/可変 -->
						<% end %>
					</td>

				</tr>
					<% end %>
			</table>

			<div class="post-comment">
				<%= form_with model: [@book, @book_comment] do |f| %>
				<%= f.text_area :comment, size: "80x10" %><br>
				<!-- :の後はカラム名 -->
				<%= f.submit "送信する" %>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
    <p>CopyRight Infratop.inc</p>
  </div>
</div>

app/views/homes/top.html.erb
<% flash.each do |message_type, message| %>
  <%= message %>
<% end %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
      </h1>
      <p>
        In <i class="fas fa-book"></i><strong>Bookers</strong>,
      </p>
      <p>you can share adn exchange your opinions, inpressions, abd enotions</p>
      <p> about various books!</p>
      <div class="btn-weapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class= "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers",root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><%= link_to ' Home', user_path(current_user), class:'fas fa-home nav-link text-light' %></li>
                <li><%= link_to ' Users', users_path,class:"fas fa-users nav-link text-light" %></li>
                <li><%= link_to ' Books', books_path, class:"fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to ' logout', user_registration_path, method: 'delete', class:"fas fa-sign-out-alt nav-link text-light"%></li>
              <% else %>
                <li><%= link_to ' Home', root_path, class:'fas fa-home nav-link text-light' %></li>
                <li><%= link_to ' About', home_about_path, class: 'fas fa-link nav-link text-light' %></li>
                <li><%= link_to ' sign up', new_user_registration_path, class:'fas fa-user-plus nav-link text-light' %></li>
                <li><%= link_to ' login', new_user_session_path, class:'fas fa-sign-in-alt nav-link text-light' %></li>
              <% end %>
            </ul>
      </div>
        </div>
      </nav>
    </header>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_profile.html.erb
<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg")%>
<table class="table">
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model: @user do |f| %>
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3>
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit "Update User" %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
</div>

<div class="col-md-8 offset-md-1">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
					<td><%= user.name%></td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>
		<%= render 'books/book', book: @book %> 
	</div>
	</div>
</div>